[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[deploy]
startCommand = "java -jar target/farm-reports-api-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/auth/login"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
